### ISSUE TITLE
change of url

### ISSUE THREAD

**Issue by ChillarAnand** [jaseemabid/act-chrome-extension#4]
recently act has changed their url & extension is unable to fetch the data

**Comment by jaseemabid** [comment]
@ChillarAnand Would you mind fixing it and sending back a PR?

**Comment by jaseemabid** [comment]
@ChillarAnand Its working just fine for me at the moment.

**Comment by ChillarAnand** [comment]
few days back, they were redirecting users based on location & now they switched back. nvm
